// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyTunes_app.api;
using MyTunes_APP.Infraestructure;

namespace MyTunes_app.api.Migrations
{
    [DbContext(typeof(MyTunes_appDbContext))]
    [Migration("20201129172415_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("MyTunes_app.api.Models.Album", b =>
                {
                    b.Property<decimal>("idalbum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("album_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("artist_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("buyalbum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("date_departure")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("img")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("price")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("rating")
                        .HasColumnType("TEXT");

                    b.Property<string>("style")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("idalbum");

                    b.ToTable("albmus");
                });

            modelBuilder.Entity("MyTunes_app.api.Models.Songs", b =>
                {
                    b.Property<double>("idsong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL");

                    b.Property<decimal?>("Albumidalbum")
                        .HasColumnType("TEXT");

                    b.Property<string>("artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("buyclick")
                        .HasColumnType("INTEGER");

                    b.Property<double>("duration")
                        .HasColumnType("REAL");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("price")
                        .HasColumnType("REAL");

                    b.Property<double>("rating")
                        .HasColumnType("REAL");

                    b.HasKey("idsong");

                    b.HasIndex("Albumidalbum");

                    b.ToTable("songs");
                });

            modelBuilder.Entity("MyTunes_app.api.Models.Songs", b =>
                {
                    b.HasOne("MyTunes_app.api.Models.Album", null)
                        .WithMany("songs")
                        .HasForeignKey("Albumidalbum");
                });

            modelBuilder.Entity("MyTunes_app.api.Models.Album", b =>
                {
                    b.Navigation("songs");
                });
#pragma warning restore 612, 618
        }
    }
}
