// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyTunes_APP.Infraestructure;

namespace MyTunes_app.api.Migrations
{
    [DbContext(typeof(MyTunes_appDbContext))]
    [Migration("20201202160325_InitialCreate2")]
    partial class InitialCreate2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("MyTunes_app.Core.Entities.Album", b =>
                {
                    b.Property<int>("Idalbum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Album_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Buyalbum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date_departure")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Duration")
                        .HasColumnType("REAL");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Idalbum");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("MyTunes_app.Core.Entities.Songs", b =>
                {
                    b.Property<int>("Idsong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Albumidalbum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Buyclick")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Duration")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.HasKey("Idsong");

                    b.HasIndex("Albumidalbum");

                    b.ToTable("Msongs");
                });

            modelBuilder.Entity("MyTunes_app.Core.Entities.Songs", b =>
                {
                    b.HasOne("MyTunes_app.Core.Entities.Album", null)
                        .WithMany("Msongs")
                        .HasForeignKey("Albumidalbum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyTunes_app.Core.Entities.Album", b =>
                {
                    b.Navigation("Msongs");
                });
#pragma warning restore 612, 618
        }
    }
}
